Paginate = 5
baseURL = "http://www.example.com"
copyright = ""
defaultContentLanguage = "en"
disqusShortname = ""
enableRobotsTXT = true
googleAnalytics = ""
preserveTaxonomyNames = true
pygmentsCodefences = true
theme = "minimo"
title = "Minimo"
[blackfriday]
hrefTargetBlank = true
[languages.en]
lang = "en"
languageName = "English"
weight = 1
[[menu.main]]
identifier = "repository"
name = "Repo"
url = "https://github.com/MunifTanjim/minimo"
weight = -10
[params.assets]
customcss = ["css/custom.css"]
customjs = ["js/custom.js"]
favicon = "favicon.ico"
gopher = ""
[params.copyright]
holder = "James Loh"
prefix = ""
startyear = "2017"
suffix = ""
[params.info]
description = "James Loh's blog"
title404 = "Nothing's here!"
[params.opengraph.facebook]
admins = []
appid = ""
pageid = ""
[params.opengraph.twitter]
page = "itsjloh"
[params.seo]
titleseparator = "•"
[params.settings]
dateformat = "2006, Jan 02"
hideentrynavigation = ["page"]
hidesocialmenu = false
homepagesections = ["recent_posts"]
listdateformat = "2006, Jan 02"
notermcloudshuffle = false
recentpostslength = 4
showreadingtime = true
[params.social]
codepen = "MunifTanjim"
email = "contact@example.com"
facebook = "MunifTanjim"
github = "MunifTanjim"
google_scholar = "qc6CJjYAAAAJ"
instagram = "MunifTanjim"
linkedin = "muniftanjim"
telegram = "MunifTanjim"
twitter = "MunifTanjim"
[params.social.config]
platforms = ["github", "facebook", "twitter", "instagram", "email", "codepen", "linkedin", "telegram", "google_scholar"]
[permalinks]
page = "/:slug/"
posts = "/posts/:slug"
[taxonomies]
author = "authors"
category = "categories"
tag = "tags"
