---
pages:
- posts/another-random-post.md
- posts/inside-foresty-post.md
hide_body: false
fields:
- name: title
  label: Title
  type: text
  hidden: false
  default: ''
- name: draft
  label: Draft
  type: boolean
  hidden: false
  default: true
- type: text
  name: slug
  label: Slug
  description: Page slug
- type: datetime
  name: publishDate
  label: Date
  description: Publish date
  config:
    required: true
  default: Invalid date
